name: ci

on:
  schedule:
      - cron: "13 4 * * *" # every day at midnight UTC (min / hour / day / month / week)
  push:
    banches:
      - '**'        # matches every branch
  workflow_dispatch:

jobs:
  test:
    name: Build project images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: docker compose build
